In [38]:
import pandas as pd
import numpy as np

In [1]:
'''

01 O sistema exportou os pedidos sem calcular o valor total de cada um. 
Corrija isso no DataFrame antes de iniciar qualquer análise.

'''

df = pd.read_csv('pedidos_narashop.csv', sep=';')
df

NameError: name 'pd' is not defined

In [48]:
df.columns

Index(['pedido_id', 'vendedor', 'categoria', 'produto', 'status_pedido',
       'quantidade', 'valor_unitario', 'prazo_entrega_dias'],
      dtype='str')

In [51]:
df['valor_total'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [53]:
df.describe()

,pedido_id,quantidade,valor_unitario,prazo_entrega_dias,valor_total
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,20000.500000,3.000550,842.816646,8.288750,2536.787685
std,5773.647028,1.416316,1130.995466,3.973583,3934.278678
min,10001.000000,1.000000,19.920000,2.000000,19.920000
25%,15000.750000,2.000000,158.202500,5.000000,377.745000
50%,20000.500000,3.000000,295.460000,8.000000,882.635000
75%,25000.250000,4.000000,1210.270000,11.000000,2650.950000
max,30000.000000,5.000000,5497.320000,18.000000,27475.250000